"""Domain and capability foundation for the voice-first interview platform."""

from .benchmark import BenchmarkReport, ProviderBenchmark
from .documents import LocalDocumentParser
from .evaluation import (
    EVALUATION_VERSION,
    DeterministicEvaluator,
    InterviewContext,
    PostInterviewEvaluationService,
    normalized_rubric,
)
from .live_voice import (
    AudioScheduler,
    LiveVoiceOrchestrator,
    LiveVoiceTurnResult,
    PrefetchedResponse,
    PrefetchGuard,
    TimestampedAudio,
)
from .models import (
    DocumentChunk,
    DocumentSource,
    InterviewMode,
    InterviewSession,
    QuestionPlan,
    RetrievedEvidence,
    SessionStatus,
    Turn,
)
from .persistence import (
    DEFAULT_RETENTION_DAYS,
    MAX_RESUME_BYTES,
    FirebaseAuthAdapter,
    FirestoreDataStore,
    FixedWindowRateLimiter,
    InMemoryAuthProvider,
    InMemoryPersistentDataStore,
    InterviewRecord,
    LocalFilesystemStorage,
    PersistenceService,
    S3CompatibleStorage,
    StoredArtifact,
    Upload,
    UploadValidator,
    UserIdentity,
    UXResource,
)
from .provider_adapters import FasterWhisperSTT, OpenRouterLLM, PiperKokoroTTS
from .retrieval import (
    DeterministicEmbeddingProvider,
    InMemoryVectorStore,
    TopicRetriever,
)
from .routing import FallbackRouter, ProviderFlags
from .session import InterviewSessionEngine, QuestionPlanner, SessionStateError
from .transport import (
    BrowserControlTransport,
    BrowserMediaTransport,
    CreateSessionRequest,
    LocalBrowserControlTransport,
    LocalSessionEventChannel,
    LocalWebRTCMediaTransport,
    RestResourceCatalog,
    SessionEvent,
    SessionEventType,
    SessionResponse,
    SignalingMessage,
    SignalingType,
    TransportValidationError,
)

__all__ = [
    "DEFAULT_RETENTION_DAYS",
    "EVALUATION_VERSION",
    "MAX_RESUME_BYTES",
    "AudioScheduler",
    "BenchmarkReport",
    "BrowserControlTransport",
    "BrowserMediaTransport",
    "CreateSessionRequest",
    "DeterministicEmbeddingProvider",
    "DeterministicEvaluator",
    "DocumentChunk",
    "DocumentSource",
    "FallbackRouter",
    "FasterWhisperSTT",
    "FirebaseAuthAdapter",
    "FirestoreDataStore",
    "FixedWindowRateLimiter",
    "InMemoryAuthProvider",
    "InMemoryPersistentDataStore",
    "InMemoryVectorStore",
    "InterviewContext",
    "InterviewMode",
    "InterviewRecord",
    "InterviewSession",
    "InterviewSessionEngine",
    "LiveVoiceOrchestrator",
    "LiveVoiceTurnResult",
    "LocalBrowserControlTransport",
    "LocalDocumentParser",
    "LocalFilesystemStorage",
    "LocalSessionEventChannel",
    "LocalWebRTCMediaTransport",
    "OpenRouterLLM",
    "PersistenceService",
    "PiperKokoroTTS",
    "PostInterviewEvaluationService",
    "PrefetchGuard",
    "PrefetchedResponse",
    "ProviderBenchmark",
    "ProviderFlags",
    "QuestionPlan",
    "QuestionPlanner",
    "RestResourceCatalog",
    "RetrievedEvidence",
    "S3CompatibleStorage",
    "SessionEvent",
    "SessionEventType",
    "SessionResponse",
    "SessionStateError",
    "SessionStatus",
    "SignalingMessage",
    "SignalingType",
    "StoredArtifact",
    "TimestampedAudio",
    "TopicRetriever",
    "TransportValidationError",
    "Turn",
    "UXResource",
    "Upload",
    "UploadValidator",
    "UserIdentity",
    "normalized_rubric",
]
