import { useEffect, useState } from 'react'

export function StatusPill({ children, tone = 'positive' }) { return <span className={`status-pill status-${tone}`}><i />{children}</span> }
export function Notice({ tone = 'info', children }) { return <div className={`notice notice-${tone}`} role={tone === 'error' ? 'alert' : 'status'}>{children}</div> }
export function Button({ children, kind = 'primary', ...props }) { return <button className={`button button-${kind}`} {...props}>{children}</button> }

export function AuthScreen({ auth, onAuthenticated }) {
  const [signup, setSignup] = useState(false)
  const [email, setEmail] = useState('candidate@example.com')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  async function submit(event) {
    event.preventDefault(); setError(''); setBusy(true)
    if (!email.includes('@')) { setError('Enter a valid email address.'); setBusy(false); return }
    try { const user = await (signup ? auth.signUp(email, password) : auth.signIn(email, password)); onAuthenticated(user) } catch { setError('Unable to authenticate. Please check your credentials and try again.') } finally { setBusy(false) }
  }
  return <main className="auth-layout"><section className="auth-intro"><span className="kicker">FIELD NOTE 12 / PRIVATE PRACTICE</span><h1>Make room for your best answer.</h1><p>A focused rehearsal room for thoughtful candidates. Bring the role, then let the conversation do the work.</p><div className="auth-mark">◎</div></section><section className="auth-card"><span className="kicker">{signup ? 'CREATE YOUR WORKSPACE' : 'WELCOME BACK'}</span><h2>{signup ? 'Start with a quiet room.' : 'Return to your practice.'}</h2><p className="muted">{signup ? 'Use your Firebase account to create a workspace.' : 'Sign in to restore your interview history.'}</p><form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} minLength="6" required /></label>{error && <Notice tone="error">{error}</Notice>}<Button type="submit" disabled={busy}>{busy ? 'Opening…' : signup ? 'Create workspace' : 'Sign in'} <span>↗</span></Button></form><button className="text-button" onClick={() => setSignup(!signup)}>{signup ? 'Already have a workspace? Sign in' : 'New here? Create a workspace'}</button><p className="fine-print">Firebase Auth · ID-token protected workspace</p></section></main>
}

export function Shell({ user, activeView, onView, onSignOut, children }) {
  const items = [['setup', 'New rehearsal', '＋'], ['active', 'Live room', '◉'], ['history', 'Past sessions', '◷'], ['results', 'Feedback', '↗']]
  return <main className="app-shell"><aside className="rail"><div className="brand"><span className="brand-mark">◎</span><span>interview<br /><em>studio</em></span></div><nav aria-label="Workspace"><span className="rail-label">YOUR WORKSPACE</span>{items.map(([key, label, icon]) => <button key={key} className={activeView === key ? 'rail-item active' : 'rail-item'} onClick={() => onView(key)}><b>{icon}</b>{label}</button>)}</nav><div className="rail-foot"><StatusPill>Local profile</StatusPill><button className="account-button" onClick={onSignOut}><span className="avatar">{user.email[0].toUpperCase()}</span><span><strong>{user.email.split('@')[0]}</strong><small>Account · Sign out</small></span></button></div></aside><section className="workspace"><header className="topbar"><span className="mobile-brand">◎ interview studio</span><span className="kicker">{activeView === 'setup' ? 'NEW REHEARSAL' : activeView === 'active' ? 'LIVE ROOM' : activeView === 'history' ? 'PAST SESSIONS' : 'FEEDBACK'}</span><StatusPill>Offline-ready</StatusPill></header>{children}<footer><span>Practice data retained for 14 days</span><span>Provider-neutral workspace · v1</span></footer></section></main>
}

export function SetupView({ onStarted, api, token }) {
  const [job, setJob] = useState(''); const [mode, setMode] = useState('technical'); const [file, setFile] = useState(null); const [error, setError] = useState(''); const [progress, setProgress] = useState(0); const [busy, setBusy] = useState(false)
  async function start() {
    const result = api.validate(job, mode, file); if (!result.valid) { setError(Object.values(result.errors)[0]); return }
    setError(''); setBusy(true); setProgress(file ? 45 : 0)
    try { const request = api.create(mode, token); const response = await fetch(request.url, request.init); if (!response.ok) throw new Error('session'); const data = await response.json(); setProgress(100); onStarted(data) } catch { setError('The local API is unavailable. Check the service and try again.') } finally { setBusy(false) }
  }
  return <section className="view fade-in"><div className="view-heading"><div><span className="kicker">01 / PREPARE</span><h1>Set the scene.</h1><p>Give your interviewer enough context to ask better questions. Your materials stay within the configured service boundary.</p></div><div className="step-note"><span>01</span><small>of 03</small></div></div><div className="setup-grid"><div className="paper-card"><label>Job description <span className="required">Required</span><textarea value={job} onChange={event => setJob(event.target.value)} placeholder="Paste the role, responsibilities, and what success looks like…" rows="9" /></label><div className="field-meta"><span>{job.length} characters</span><span>Untrusted content is isolated</span></div></div><div className="setup-side"><label>Resume <span className="optional">Optional PDF</span><input className="file-input" type="file" accept="application/pdf" onChange={event => setFile(event.target.files[0] || null)} /><span className="upload-box"><b>↑</b><strong>{file ? file.name : 'Choose a resume'}</strong><small>{file ? `${Math.round(file.size / 1024)} KB selected` : 'PDF up to 10 MB'}</small></span></label>{progress > 0 && <div className="progress"><span style={{ width: `${progress}%` }} /></div>}<fieldset><legend>Interview mode</legend><label className="mode-option"><input type="radio" checked={mode === 'recruiter'} onChange={() => setMode('recruiter')} /><span><b>Recruiter screen</b><small>Motivation, fit, communication</small></span></label><label className="mode-option"><input type="radio" checked={mode === 'technical'} onChange={() => setMode('technical')} /><span><b>Technical / hiring manager</b><small>Depth, reasoning, project evidence</small></span></label></fieldset></div></div>{error && <Notice tone="error">{error}</Notice>}<div className="action-row"><span className="muted">You can change these details before each session.</span><Button onClick={start} disabled={busy}>{busy ? 'Creating room…' : 'Create interview room'} <span>↗</span></Button></div></section>
}

export function ActiveView({ session, onComplete, transport, media }) {
  const [muted, setMuted] = useState(false); const [connection, setConnection] = useState('connecting'); const [mic, setMic] = useState('idle'); const [transcript, setTranscript] = useState('Your words will appear here as you speak…'); const [status, setStatus] = useState('Opening secure local control channel')
  useEffect(() => { if (!transport) return undefined; transport.connect(); return () => transport.disconnect() }, [transport])
  useEffect(() => { if (!transport) return undefined; transport.setEventHandler(event => { if (event.type === 'connection') { setConnection(event.payload.state); setStatus(event.payload.state === 'connected' ? 'Control channel connected' : 'Control channel reconnecting') } if (event.type === 'transcript.partial' || event.type === 'transcript.final') setTranscript(event.payload.text || '') }); return () => transport.setEventHandler(() => {}) }, [transport])
  async function requestMic() { try { await media?.requestMicrophone(); setMic('ready') } catch { setMic('denied') } }
  function reconnect() { transport?.connect(); setStatus('Reconnecting control channel') }
  return <section className="view fade-in"><div className="view-heading compact"><div><span className="kicker">02 / LIVE ROOM</span><h1>Stay with the moment.</h1><p>{session?.mode === 'recruiter' ? 'Recruiter screen' : 'Technical / hiring manager'} · {status}</p></div><StatusPill tone={connection === 'connected' ? 'positive' : 'warning'}>{connection === 'connected' ? 'Connected' : connection === 'failed' ? 'Unavailable' : 'Reconnecting'}</StatusPill></div><div className="live-grid"><div className="live-card"><div className={`voice-orb ${muted ? 'muted' : ''}`}><span>{muted ? 'Ⅱ' : '●'}</span></div><p className="live-caption">{muted ? 'Microphone muted' : 'Your interviewer is listening'}</p><div className="control-row"><Button kind="quiet" onClick={() => { setMuted(!muted); transport?.interrupt() }}>{muted ? 'Unmute' : 'Mute'}</Button><Button kind="quiet" onClick={reconnect}>Reconnect</Button><Button kind="danger" onClick={() => { transport?.cancel(); onComplete() }}>Stop interview</Button></div>{mic === 'denied' && <Notice tone="error">Microphone permission was denied. Allow access in your browser settings, then try again.</Notice>}{mic !== 'ready' && <button className="permission-link" onClick={requestMic}>Check microphone permission</button>}</div><div className="transcript-card"><div className="card-label"><span>Live transcript</span><span className="pulse">● {connection}</span></div><div className="transcript-line"><span>INTERVIEWER</span><p>Tell me about a project where you had to make a difficult trade-off.</p></div><div className="transcript-line candidate"><span>YOU · LIVE</span><p className={transcript.startsWith('Your words') ? 'muted' : ''}>{transcript}</p></div><div className="interruption">↯ <span>Interruptions are welcome. Pause or correct yourself naturally.</span></div></div></div></section>
}

export function HistoryView({ history, loading, onOpen, onDelete }) {
  if (loading) return <section className="view"><Notice>Loading your practice history…</Notice></section>
  return <section className="view fade-in"><div className="view-heading"><div><span className="kicker">03 / PAST SESSIONS</span><h1>Notice your progress.</h1><p>Every rehearsal is a note to your future self. Records expire automatically after 14 days.</p></div></div>{history.length === 0 ? <div className="empty-state"><span>◷</span><h2>Your first rehearsal is waiting.</h2><p>Complete a live room and its transcript, replay, and feedback will gather here.</p></div> : <div className="history-list">{history.map(item => <article className="history-item" key={item.id}><div className="date-stamp"><span>{item.mode === 'technical' ? 'TECH' : 'RECRUIT'}</span><small>14 DAYS</small></div><div><h3>{item.mode === 'technical' ? 'Technical / hiring manager' : 'Recruiter screen'}</h3><p>{item.status} · Local session</p></div><div className="history-actions"><button onClick={() => onOpen(item.id)}>Open record ↗</button><button onClick={() => onDelete(item.id)} aria-label={`Delete ${item.id}`}>Delete</button></div></article>)}</div>}</section>
}

export function ResultsView() { return <section className="view fade-in"><div className="view-heading"><div><span className="kicker">04 / FEEDBACK</span><h1>Feedback that points forward.</h1><p>Complete a session to unlock evidence-linked evaluation, transcript, and recommendations.</p></div></div><div className="result-empty"><div className="score-placeholder">--<small>/ 100</small></div><div><h2>Your next useful note is earned in the room.</h2><p className="muted">No completed evaluation is available yet. The evaluator only reads final candidate transcript segments after completion.</p><Button onClick={() => window.dispatchEvent(new CustomEvent('go-setup'))}>Start a rehearsal</Button></div></div></section> }
